# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under gcp_uc/resources/*
# and gcp_uc/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for gcp_uc Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./gcp_uc

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: gcp_uc-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.236.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t eric_staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t eric_staging
